version: '3.6'

volumes:
    data:

services:
    db:
        image: postgres:13-alpine
        restart: unless-stopped
        volumes:
            - 'data:/var/lib/postgresql/data'
        environment:
            - POSTGRES_PASSWORD=oskour

    go_app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        depends_on:
            - 'db'
        ports:
            - 8000:8000
        environment:
            - IP=0.0.0.0
            - PORT=8000
            - POSTGRES_URL='db'
            - POSTGRES_PASSWORD=oskour

    swagger:
        image: swaggerapi/swagger-ui
        restart: unless-stopped
        depends_on:
            - 'go_app'
        volumes:
            - './openapi.yml:/openapi.yml'
        ports:
            - 80:8080
        environment:
            - SWAGGER_JSON=/openapi.yml

